openapi: '3.0.2'
info:
  title: Avengers Crime Report
  description: "Made for Ungraded Challenge Phase 2 FTGO"
  version: '1.0'
  contact:
    name: "Daniel Osvaldo Rahmanto"
    email: "daniel@mail.com"
servers:
  - url: 'http://localhost:8080'
    description: 'development'
paths:
  '/crimereports':
    get:
      summary: 'Get all crime reports'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrimeReports'
        '500':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

    post:
      summary: 'Post a new crime report'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostRequest'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrimePosted'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '500':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

  '/crimereports/{id}':
    get:
      summary: 'Get crime report by id'
      parameters:
        - name: crimeId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrimeReport'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '500':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
                
    put:
      summary: 'Update crime report'
      parameters:
        - name: crimeId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutRequest'

      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrimePut'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '500':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

    delete:
      summary: 'Delete crime by id'
      parameters:
        - name: crimeId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrimeDeleted'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '500':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

components:
  schemas:
    CrimeReport:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 200
        message:
          type: string
          example: 'Get crime reports'
        data:
          $ref: '#/components/schemas/Report'
            
    CrimeReports:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 200
        message:
          type: string
          example: 'Get crime reports'
        data:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/Report'
              - $ref: '#/components/schemas/Report2'

    Report:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 1
        hero:
          $ref: '#/components/schemas/Hero'
        villain:
          $ref: '#/components/schemas/Villain'
        description:
          type: string
          example: "some description"
        date:
          type: string
          format: date
          example: '2021-01-01'
    
    CrimePosted:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 201
        message:
          type: string
          example: 'Crime report posted'
        data:
          $ref: '#/components/schemas/PostRequest'

    CrimePut:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 200
        message:
          type: string
          example: 'Crime report updated on id = crimeId'
        data:
          $ref: '#/components/schemas/PutRequest'

    CrimeDeleted:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 200
        message:
          type: string
          example: 'Crime deleted on id = crimeId'
        data:
          type: string
          example: null

    PostRequest:
      type: object
      properties:
        hero_id:
          type: integer
          format: int32
          example: 1
        villain_id:
          type: integer
          format: int32
          example: 1
        description:
          type: string
          example: 'some description'
        date:
          type: string
          format: date
          example: '2021-01-01'

    PutRequest:
      type: object
      properties:
        description:
          type: string
          example: 'some description'
        date:
          type: string
          format: date
          example: '2021-01-01'

    Hero:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 1
        name:
          type: string
          example: 'Doctor Strange'
        universe:
          type: string
          example: 'Earth'
        skill:
          type: string
          example: 'Manipulate time'
        imgurl:
          type: string
          example: 'https://somelink.com'

    Villain:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 1
        name:
          type: string
          example: 'Dormammu'
        universe:
          type: string
          example: 'Galaxy'
        imgurl:
          type: string
          example: 'https://somelink.com'

    Report2:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 2
        hero:
          $ref: '#/components/schemas/Hero2'
        villain:
          $ref: '#/components/schemas/Villain2'
        description:
          type: string
          example: "some description"
        date:
          type: string
          format: date
          example: '2019-01-01'

    Hero2:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 2
        name:
          type: string
          example: 'Hulk'
        universe:
          type: string
          example: 'Earth'
        skill:
          type: string
          example: 'Turning into a giant'
        imgurl:
          type: string
          example: 'https://somelink.com'

    Villain2:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 2
        name:
          type: string
          example: 'Abomination'
        universe:
          type: string
          example: 'Earth-616'
        imgurl:
          type: string
          example: 'https://somelink.com'
    
    BadRequest:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 400
        message:
          type: string
          example: 'Bad request'
        data:
          type: string
          example: null

    NotFound:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 404
        message:
          type: string
          example: 'Not Found'
        data:
          type: string
          example: null
  
    InternalServerError:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 500
        message:
          type: string
          example: 'Internal server error'
        data:
          type: string
          example: null