openapi: '3.0.2'
info:
  title: Avengers Crime Report
  description: "Made for Ungraded Challenge Phase 2 FTGO"
  version: '1.0'
  contact:
    name: "Daniel Osvaldo Rahmanto"
    email: "daniel@mail.com"
servers:
  - url: 'http://localhost:8080'
    description: 'development'
paths:
  '/crimereports':
    get:
      summary: 'get all crime reports'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hero'

    post:
      summary: 'post a new crime report'
      responses:
        '200':
          description: OK

  '/crimereports/{id}':
    get:
      summary: 'get crime report by id'
      parameters:
        - name: crimeId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: ok


components:
  schemas:
    Hero:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 1
        name:
          type: string
          example: 'Doctor Strange'
        universe:
          type: string
          example: 'Earth'
        skill:
          type: string
          example: 'Manipulate time'
        imgurl:
          type: string
          example: 'https://somelink.com'
    Villain:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 1
        name:
          type: string
          example: 'Dormammu'
        universe:
          type: string
          example: 'Galaxy'
        imgurl:
          type: string
          example: 'https://somelink.com'
  