openapi: '3.0.2'
info:
  title: Avengers Crime Report
  description: "Made for Ungraded Challenge Phase 2 FTGO"
  version: '1.0'
  contact:
    name: "Daniel Osvaldo Rahmanto"
    email: "daniel@mail.com"
servers:
  - url: 'http://localhost:8080'
    description: 'development'
paths:
  '/crimereports':
    get:
      summary: 'Get all crime reports'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrimeReports'

    post:
      summary: 'Post a new crime report'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                hero_id:
                  type: integer
                  format: int32
                  example: 1
                villain_id:
                  type: integer
                  format: int32
                  example: 1
                description:
                  type: string
                  example: 'some description'
                date:
                  type: string
                  format: date
                  example: '2021-01-01'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrimePosted'

  '/crimereports/{id}':
    get:
      summary: 'Get crime report by id'
      parameters:
        - name: crimeId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrimeReport'
    put:
      summary: 'Update crime report'
      parameters:
        - name: crimeId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                  example: 'some description'
                date:
                  type: string
                  format: date
                  example: '2021-01-01'
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrimePut'

    delete:
      summary: 'Delete crime by id'
      parameters:
        - name: crimeId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrimeDeleted'

components:
  schemas:
    CrimeReport:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 200
        message:
          type: string
          example: 'Get crime reports'
        data:
          $ref: '#/components/schemas/Report'
            
    CrimeReports:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 200
        message:
          type: string
          example: 'Get crime reports'
        data:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/Report'
              - $ref: '#/components/schemas/Report'

    Report:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 1
        hero:
          $ref: '#/components/schemas/Hero'
        villain:
          $ref: '#/components/schemas/Villain'
        description:
          type: string
          example: "some description"
        date:
          type: string
          format: date
          example: '2021-01-01'
    
    CrimePosted:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 201
        message:
          type: string
          example: 'Crime report posted'
        data:
          type: string
          example: null

    CrimePut:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 200
        message:
          type: string
          example: 'Crime report updated on id = crimeId'
        data:
          type: string
          example: null

    CrimeDeleted:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 200
        message:
          type: string
          example: 'Crime deleted on id = crimeId'
        data:
          type: string
          example: null

    Hero:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 1
        name:
          type: string
          example: 'Doctor Strange'
        universe:
          type: string
          example: 'Earth'
        skill:
          type: string
          example: 'Manipulate time'
        imgurl:
          type: string
          example: 'https://somelink.com'

    Villain:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 1
        name:
          type: string
          example: 'Dormammu'
        universe:
          type: string
          example: 'Galaxy'
        imgurl:
          type: string
          example: 'https://somelink.com'