CREATE DATABASE p2_ungraded_6;

CREATE TABLE users(
    id INT AUTO_INCREMENT NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    age INT UNSIGNED NOT NULL,
    occupation VARCHAR(100) NOT NULL,
    role VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE recipes(
    id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NOT NULL,
    duration FLOAT UNSIGNED NOT NULL,
    rating FLOAT UNSIGNED NOT NULL,
    PRIMARY KEY (id)
);